### ISSUE TITLE
[Feat] - 마이페이지 (선생님) : 내가 등록한 클래스

### ISSUE THREAD

**Issue by hyun0zin** [ClassRoom-Project/ClassRoom-Project#16]
📕 Issue Feature

마이페이지 (선생님) : 내가 등록한 클래스 

🧾Todo

수행해야 하는 or 수행한 작업 목록을 입력하세요

- [x] 로그인한 사람의 user_id로 등록된 class 정보 불러오기
- [x] 수강생 리스트 페이지로 이동하기
- [ ] 클래스 삭제하기 -> 삭제하기 누르면 active 상태 false로 바뀌면서 비활성 되게 하기 (튜터님 피드백)
- [x] 클래스 상세보기 페이지로 이동하기

- [ ] 💬 생각할 부분 : 예약한 유저가 있는지? 예약한 사람이 있으면 클래스가 삭제되면 알림이 가는지? 메세지가 가는지? 혹은 예약한 수강생이 있다면 삭제가 안 되도록?
- [x] 💬 생각할 부분 : 클래스를 등록하고 예약한 수강생이 있으면 수강생 정보를 확인 할 수 있는 공간이 있어야 함...! 이부분 팀원들이랑 얘기 나누기 -> 클래스 보러가기 옆에 예약자 명단 보러가기? 같은거 눌러서 해당 페이지로 이동 할 수 있도록 ! => 단체 채팅 열기 기능도 있으면 좋을듯

**Comment by CaesiumY** [comment]
보통 바로 삭제하기 보다는 비활성화 같은 걸로 상태를 바꿔주는 편입니다!
