### ISSUE TITLE
[Feat] 결제 취소 및 결제 실패 페이지 구현

### ISSUE THREAD

**Issue by anywhereim** [ClassRoom-Project/ClassRoom-Project#99]
📕 Issue Feature
결제 취소 및 결제 실패 페이지 구현

🧾Todo

- [x] 결제 취소 시 리다이렉트 방법 찾아보기(toss api 커스텀 필요해보임 ..!) - 지원님
- [x] 결제 실패 시 페이지 구현 (디자인 아직 나오지 않음)

**Comment by seopport** [comment]
미주님! 제가 예약 완료 로직 수정하면서 실패 리다이렉트 처리 해놓았어요!! 페이지 구현만 하면 될것같습니당
채팅.. 기능 바쁘실 것 같은데 필요하시면 제가 실패 페이지까지 구현해볼께용 말씀해주세요~!!

**Comment by anywhereim** [comment]
아앗.... 여기 댓글달아주신지 모르고 어제 여쭤봤었네요😂
